output(pgui_version())
output(pgui_backend())

pgui_window("PGUI Demo", 680, 420)
pgui_label("PGUI is Prism's native GTK3-style GUI toolkit.")
pgui_label("It is built into the C interpreter core without GTK, third-party modules, or language bindings.")
pgui_separator()
pgui_input("Type something...")
pgui_button("Apply")
pgui_button("Close")
pgui_run("pgui_demo.html")